version: '3'
services:
  mongodb-burger:
    image: mongo
    container_name: "mongodb-tweets"
    environment:
      - MONGO_INITDB_DATABASE=tweets-db
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=welcome1
    volumes:
      - mongodb:/data/tweets/db
    ports:
      - 27017:27017
    networks:
      - mongo_net

volumes:
  mongodb:

networks:
  mongo_net:
    driver: bridge