

CREATE TABLE ACCOUNT_SUMMARY (ID SERIAL NOT NULL PRIMARY KEY, ACCOUNT_NUMBER TEXT NOT NULL,
                                CURRENT_BALANCE NUMERIC(10, 5));

INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('51524');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('719106');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('209766');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('424978');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('709443');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('529933');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('221416');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('881616');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('494514');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('302370');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('455515');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('486655');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('254179');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('549538');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('938606');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('12065');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('762420');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('698261');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('90518');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('483374');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('548709');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('193379');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('517684');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('600668');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('233085');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('501971');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('35706');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('769783');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('894781');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('830340');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('789636');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('891341');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('18985');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('281220');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('170502');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('222808');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('897606');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('108554');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('751899');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('226986');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('944403');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('520722');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('742028');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('445057');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('82405');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('308055');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('661871');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('986940');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('710826');
INSERT INTO ACCOUNT_SUMMARY (ACCOUNT_NUMBER) VALUES ('89988');

CREATE TABLE TRANSACTION (ACCOUNT_SUMMARY_ID NUMERIC NOT NULL PRIMARY KEY , TIMESTAMP TIMESTAMP NOT NULL,
                            AMOUNT NUMERIC(10,5) NOT NULL);




truncate table batch_job_execution cascade;
truncate table batch_job_instance cascade;